IMPORT

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

LOADING DATASETS

In [3]:
import sys
import os

sys.path.append(os.path.abspath(".."))

from src.load_data import load_all_data

dfs = load_all_data()


BASIC EDA

In [4]:
for name, df in dfs.items():

    print("\n" + "=" * 60)
    print(f"{name.upper()} DATAFRAME")
    print("=" * 60)

    # First rows
    print("\nHEAD:")
    display(df.tail(25))

    # Shape
    print(f"\nShape: {df.shape}")

    # Column names
    print("\nColumns:")
    print(df.columns.tolist())

    # Info
    print("\nINFO:")
    df.info()

    # Missing values
    print("\nMISSING VALUES:")
    print(df.isnull().sum())

    # Duplicates
    print(f"\nDuplicate rows: {df.duplicated().sum()}")

    # Data types
    print("\nData Types:")
    print(df.dtypes)

    print("\n")

============================================================
CIRCUITS DATAFRAME
============================================================

HEAD:

,circuit_id,circuit_name,locality,country,lat,lng,url
53,pescara,Pescara Circuit,Pescara,Italy,42.47500,14.150800,https://en.wikipedia.org/wiki/Pescara_Circuit
54,phoenix,Phoenix street circuit,Phoenix,USA,33.44790,-112.075000,https://en.wikipedia.org/wiki/Phoenix_street_c...
55,portimao,Autódromo Internacional do Algarve,Portimão,Portugal,37.22700,-8.626700,https://en.wikipedia.org/wiki/Algarve_Internat...
56,red_bull_ring,Red Bull Ring,Spielberg,Austria,47.21970,14.764700,https://en.wikipedia.org/wiki/Red_Bull_Ring
57,reims,Reims-Gueux,Reims,France,49.25420,3.930830,https://en.wikipedia.org/wiki/Reims-Gueux
58,ricard,Circuit Paul Ricard,Le Castellet,France,43.25060,5.791670,https://en.wikipedia.org/wiki/Circuit_Paul_Ricard
59,riverside,Riverside International Raceway,California,USA,33.93700,-117.273000,https://en.wikipedia.org/wiki/Riverside_Intern...
60,rodriguez,Autódromo Hermanos Rodríguez,Mexico City,Mexico,19.40420,-99.090700,https://en.wikipedia.org/wiki/Aut%C3%B3dromo_H...
61,sebring,Sebring International Raceway,Florida,USA,27.45470,-81.348300,https://en.wikipedia.org/wiki/Sebring_Internat...
62,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.738000,https://en.wikipedia.org/wiki/Sepang_Internati...
63,shanghai,Shanghai International Circuit,Shanghai,China,31.33890,121.220000,https://en.wikipedia.org/wiki/Shanghai_Interna...
64,silverstone,Silverstone Circuit,Silverstone,UK,52.07860,-1.016940,https://en.wikipedia.org/wiki/Silverstone_Circuit
65,sochi,Sochi Autodrom,Sochi,Russia,43.40570,39.957800,https://en.wikipedia.org/wiki/Sochi_Autodrom
66,spa,Circuit de Spa-Francorchamps,Spa,Belgium,50.43720,5.971390,https://en.wikipedia.org/wiki/Circuit_de_Spa-F...
67,suzuka,Suzuka Circuit,Suzuka,Japan,34.84310,136.541000,https://en.wikipedia.org/wiki/Suzuka_Internati...
68,tremblant,Circuit Mont-Tremblant,Quebec,Canada,46.18770,-74.609900,https://en.wikipedia.org/wiki/Circuit_Mont-Tre...
69,valencia,Valencia Street Circuit,Valencia,Spain,39.45890,-0.331667,https://en.wikipedia.org/wiki/Valencia_Street_...
70,vegas,Las Vegas Strip Street Circuit,Las Vegas,USA,36.11470,-115.173000,https://en.wikipedia.org/wiki/Las_Vegas_Grand_...
71,villeneuve,Circuit Gilles Villeneuve,Montreal,Canada,45.50000,-73.522800,https://en.wikipedia.org/wiki/Circuit_Gilles_V...
72,watkins_glen,Watkins Glen,New York State,USA,42.33690,-76.927200,https://en.wikipedia.org/wiki/Watkins_Glen_Int...
73,yas_marina,Yas Marina Circuit,Abu Dhabi,UAE,24.46720,54.603100,https://en.wikipedia.org/wiki/Yas_Marina_Circuit
74,yeongam,Korean International Circuit,Yeongam County,Korea,34.73330,126.417000,https://en.wikipedia.org/wiki/Korea_Internatio...
75,zandvoort,Circuit Park Zandvoort,Zandvoort,Netherlands,52.38880,4.540920,https://en.wikipedia.org/wiki/Circuit_Zandvoort
76,zeltweg,Zeltweg,Styria,Austria,47.20390,14.747800,https://en.wikipedia.org/wiki/Zeltweg_Air_Base
77,zolder,Zolder,Heusden-Zolder,Belgium,50.98940,5.256940,https://en.wikipedia.org/wiki/Circuit_Zolder

Shape: (78, 7)

Columns:
['circuit_id', 'circuit_name', 'locality', 'country', 'lat', 'lng', 'url']

INFO:
<class 'pandas.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   circuit_id    78 non-null     str
 1   circuit_name  78 non-null     str
 2   locality      78 non-null     str
 3   country       78 non-null     str
 4   lat           78 non-null     float64
 5   lng           78 non-null     float64
 6   url           78 non-null     str
dtypes: float64(2), str(5)
memory usage: 4.4 KB

MISSING VALUES:
circuit_id      0
circuit_name    0
locality        0
country         0
lat             0
lng             0
url             0
dtype: int64

Duplicate rows: 0

Data Types:
circuit_id          str
circuit_name        str
locality            str
country             str
lat             float64
lng             float64
url                 str
dtype: object



============================================================
CONSTRUCTORS DATAFRAME
============================================================

HEAD:

,constructor_id,name,nationality,url
189,super_aguri,Super Aguri,Japanese,https://en.wikipedia.org/wiki/Super_Aguri_F1
190,surtees,Surtees,British,https://en.wikipedia.org/wiki/Surtees
191,sutton,Sutton,American,https://en.wikipedia.org/wiki/Sutton_(construc...
192,team_lotus,Team Lotus,British,https://en.wikipedia.org/wiki/Team_Lotus
193,tec-mec,Tec-Mec,Italian,https://en.wikipedia.org/wiki/Tec-Mec
194,tecno,Tecno,Italian,https://en.wikipedia.org/wiki/Tecno
195,theodore,Theodore,Hong Kong,https://en.wikipedia.org/wiki/Theodore_Racing
196,token,Token,British,https://en.wikipedia.org/wiki/Token_Racing
197,toleman,Toleman,British,https://en.wikipedia.org/wiki/Toleman
198,tomaso,De Tomaso,Italian,https://en.wikipedia.org/wiki/De_Tomaso
199,toro_rosso,Toro Rosso,Italian,https://en.wikipedia.org/wiki/Scuderia_Toro_Rosso
200,toyota,Toyota,Japanese,https://en.wikipedia.org/wiki/Toyota_Racing
201,trevis,Trevis,American,https://en.wikipedia.org/wiki/Trevis
202,trojan,Trojan,British,https://en.wikipedia.org/wiki/Trojan–Tauranac_...
203,turner,Turner,American,https://en.wikipedia.org/wiki/Turner_(construc...
204,tyrrell,Tyrrell,British,https://en.wikipedia.org/wiki/Tyrrell_Racing
205,vanwall,Vanwall,British,https://en.wikipedia.org/wiki/Vanwall
206,veritas,Veritas,German,https://en.wikipedia.org/wiki/Veritas_(automob...
207,vhristensen,Christensen,American,https://en.wikipedia.org/wiki/Christensen_(con...
208,virgin,Virgin,British,https://en.wikipedia.org/wiki/Virgin_Racing
209,watson,Watson,American,https://en.wikipedia.org/wiki/A._J._Watson
210,wetteroth,Wetteroth,American,https://en.wikipedia.org/wiki/Wetteroth
211,williams,Williams,British,https://en.wikipedia.org/wiki/Williams_Racing
212,wolf,Wolf,Canadian,https://en.wikipedia.org/wiki/Walter_Wolf_Racing
213,zakspeed,Zakspeed,German,https://en.wikipedia.org/wiki/Zakspeed

Shape: (214, 4)

Columns:
['constructor_id', 'name', 'nationality', 'url']

INFO:
<class 'pandas.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   constructor_id  214 non-null    str
 1   name            214 non-null    str
 2   nationality     214 non-null    str
 3   url             214 non-null    str
dtypes: str(4)
memory usage: 6.8 KB

MISSING VALUES:
constructor_id    0
name              0
nationality       0
url               0
dtype: int64

Duplicate rows: 0

Data Types:
constructor_id    str
name              str
nationality       str
url               str
dtype: object



============================================================
CONSTRUCTOR_STANDINGS DATAFRAME
============================================================

HEAD:

     season  position  points  wins constructor_id       constructor
899    2024       7.0    58.0     0           haas      Haas F1 Team
900    2024       8.0    46.0     0             rb        RB F1 Team
901    2024       9.0    17.0     0       williams          Williams
902    2024      10.0     4.0     0         sauber            Sauber
903    2025       1.0   833.0    14        mclaren           McLaren
904    2025       2.0   469.0     2       mercedes          Mercedes
905    2025       3.0   451.0     8       red_bull          Red Bull
906    2025       4.0   398.0     0        ferrari           Ferrari
907    2025       5.0   137.0     0       williams          Williams
908    2025       6.0    92.0     0             rb        RB F1 Team
909    2025       7.0    89.0     0   aston_martin      Aston Martin
910    2025       8.0    79.0     0           haas      Haas F1 Team
911    2025       9.0    70.0     0         sauber            Sauber
912    2025      10.0    22.0     0         alpine    Alpine F1 Team
913    2026       1.0   135.0     3       mercedes          Mercedes
914    2026       2.0    90.0     0        ferrari           Ferrari
915    2026       3.0    46.0     0        mclaren           McLaren
916    2026       4.0    18.0     0           haas      Haas F1 Team
917    2026       5.0    16.0     0         alpine    Alpine F1 Team
918    2026       6.0    16.0     0       red_bull          Red Bull
919    2026       7.0    14.0     0             rb        RB F1 Team
920    2026       8.0     2.0     0           audi              Audi
921    2026       9.0     2.0     0       williams          Williams
922    2026      10.0     0.0     0       cadillac  Cadillac F1 Team
923    2026      11.0     0.0     0   aston_martin      Aston Martin

Shape: (924, 6)

Columns:
['season', 'position', 'points', 'wins', 'constructor_id', 'constructor']

INFO:
<class 'pandas.DataFrame'>
RangeIndex: 924 entries, 0 to 923
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   season          924 non-null    int64
 1   position        712 non-null    float64
 2   points          924 non-null    float64
 3   wins            924 non-null    int64
 4   constructor_id  924 non-null    str
 5   constructor     924 non-null    str
dtypes: float64(2), int64(2), str(2)
memory usage: 43.4 KB

MISSING VALUES:
season              0
position          212
points              0
wins                0
constructor_id      0
constructor         0
dtype: int64

Duplicate rows: 0

Data Types:
season              int64
position          float64
points            float64
wins                int64
constructor_id        str
constructor           str
dtype: object



============================================================
DRIVERS DATAFRAME
============================================================

HEAD:

,driver_id,given_name,family_name,dob,nationality,number,code,url
854,dryver,Bernard,de Dryver,1952-09-19,Belgian,NaN,NaN,http://en.wikipedia.org/wiki/Bernard_de_Dryver
855,filippis,Maria,de Filippis,1926-11-11,Italian,NaN,NaN,http://en.wikipedia.org/wiki/Maria_Teresa_de_F...
856,graffenried,Toulo,de Graffenried,1914-05-18,Swiss,NaN,NaN,http://en.wikipedia.org/wiki/Toulo_de_Graffenried
857,klerk,Peter,de Klerk,1935-03-16,South African,NaN,NaN,http://en.wikipedia.org/wiki/Peter_de_Klerk
858,portago,Alfonso,de Portago,1928-10-11,Spanish,NaN,NaN,http://en.wikipedia.org/wiki/Alfonso_de_Portago
859,riu,Giovanni,de Riu,1925-03-10,Italian,NaN,NaN,http://en.wikipedia.org/wiki/Giovanni_de_Riu
860,terra,Max,de Terra,1918-10-06,Swiss,NaN,NaN,http://en.wikipedia.org/wiki/Max_de_Terra
861,tomaso,Alessandro,de Tomaso,1928-07-10,Argentine,NaN,NaN,http://en.wikipedia.org/wiki/Alessandro_de_Tomaso
862,tornaco,Charles,de Tornaco,1927-06-07,Belgian,NaN,NaN,http://en.wikipedia.org/wiki/Charles_de_Tornaco
863,villota,Emilio,de Villota,1946-07-26,Spanish,NaN,NaN,http://en.wikipedia.org/wiki/Emilio_de_Villota
864,vos,Ernie,de Vos,1941-07-01,Dutch,NaN,NaN,http://en.wikipedia.org/wiki/Ernie_de_Vos
865,de_vries,Nyck,de Vries,1995-02-06,Dutch,21.0,DEV,http://en.wikipedia.org/wiki/Nyck_de_Vries
866,rosa,Pedro,de la Rosa,1971-02-24,Spanish,NaN,DLR,http://en.wikipedia.org/wiki/Pedro_de_la_Rosa
867,grassi,Lucas,di Grassi,1984-08-11,Brazilian,NaN,DIG,http://en.wikipedia.org/wiki/Lucas_di_Grassi
868,resta,Paul,di Resta,1986-04-16,British,40.0,DIR,http://en.wikipedia.org/wiki/Paul_di_Resta
869,lennep,Gijs,van Lennep,1942-03-16,Dutch,NaN,NaN,http://en.wikipedia.org/wiki/Gijs_Van_Lennep
870,rooyen,Basil,van Rooyen,1939-04-19,South African,NaN,NaN,http://en.wikipedia.org/wiki/Basil_van_Rooyen
871,poele,Eric,van de Poele,1961-09-30,Belgian,NaN,NaN,http://en.wikipedia.org/wiki/Eric_van_de_Poele
872,garde,Giedo,van der Garde,1985-04-25,Dutch,NaN,VDG,http://en.wikipedia.org/wiki/Giedo_van_der_Garde
873,lof,Dries,van der Lof,1919-08-23,Dutch,NaN,NaN,http://en.wikipedia.org/wiki/Dries_van_der_Lof
874,vyver,Syd,van der Vyver,1920-06-01,South African,NaN,NaN,http://en.wikipedia.org/wiki/Syd_van_der_Vyver
875,opel,Rikky,von Opel,1947-10-14,Liechtensteiner,NaN,NaN,http://en.wikipedia.org/wiki/Rikky_von_Opel
876,hans_stuck,Hans,von Stuck,1900-12-27,German,NaN,NaN,http://en.wikipedia.org/wiki/Hans_Von_Stuck
877,trips,Wolfgang,von Trips,1928-05-04,German,NaN,NaN,http://en.wikipedia.org/wiki/Wolfgang_Graf_Ber...
878,etancelin,Philippe,Étancelin,1896-12-28,French,NaN,NaN,http://en.wikipedia.org/wiki/Philippe_%C3%89ta...

Shape: (879, 8)

Columns:
['driver_id', 'given_name', 'family_name', 'dob', 'nationality', 'number', 'code', 'url']

INFO:
<class 'pandas.DataFrame'>
RangeIndex: 879 entries, 0 to 878
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   driver_id    879 non-null    str
 1   given_name   879 non-null    str
 2   family_name  879 non-null    str
 3   dob          865 non-null    str
 4   nationality  865 non-null    str
 5   number       63 non-null     float64
 6   code         107 non-null    str
 7   url          865 non-null    str
dtypes: float64(1), str(7)
memory usage: 55.1 KB

MISSING VALUES:
driver_id        0
given_name       0
family_name      0
dob             14
nationality     14
number         816
code           772
url             14
dtype: int64

Duplicate rows: 0

Data Types:
driver_id          str
given_name         str
family_name        str
dob                str
nationality        str
number         float64
code               str
url                str
dtype: object



============================================================
DRIVER_STANDINGS DATAFRAME
============================================================

HEAD:

      season  position  points  wins       driver_id       constructor
3103    2025      19.0    19.0     0       bortoleto            Sauber
3104    2025      20.0     0.0     0       colapinto    Alpine F1 Team
3105    2025      21.0     0.0     0          doohan    Alpine F1 Team
3106    2026       1.0    72.0     2       antonelli          Mercedes
3107    2026       2.0    63.0     1         russell          Mercedes
3108    2026       3.0    49.0     0         leclerc           Ferrari
3109    2026       4.0    41.0     0        hamilton           Ferrari
3110    2026       5.0    25.0     0          norris           McLaren
3111    2026       6.0    21.0     0         piastri           McLaren
3112    2026       7.0    17.0     0         bearman      Haas F1 Team
3113    2026       8.0    15.0     0           gasly    Alpine F1 Team
3114    2026       9.0    12.0     0  max_verstappen          Red Bull
3115    2026      10.0    10.0     0          lawson        RB F1 Team
3116    2026      11.0     4.0     0  arvid_lindblad        RB F1 Team
3117    2026      12.0     4.0     0          hadjar          Red Bull
3118    2026      13.0     2.0     0       bortoleto              Audi
3119    2026      14.0     2.0     0           sainz          Williams
3120    2026      15.0     1.0     0            ocon      Haas F1 Team
3121    2026      16.0     1.0     0       colapinto    Alpine F1 Team
3122    2026      17.0     0.0     0      hulkenberg              Audi
3123    2026      18.0     0.0     0           albon          Williams
3124    2026      19.0     0.0     0          bottas  Cadillac F1 Team
3125    2026      20.0     0.0     0           perez  Cadillac F1 Team
3126    2026      21.0     0.0     0          alonso      Aston Martin
3127    2026      22.0     0.0     0          stroll      Aston Martin

Shape: (3128, 6)

Columns:
['season', 'position', 'points', 'wins', 'driver_id', 'constructor']

INFO:
<class 'pandas.DataFrame'>
RangeIndex: 3128 entries, 0 to 3127
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   season       3128 non-null   int64
 1   position     1664 non-null   float64
 2   points       3128 non-null   float64
 3   wins         3128 non-null   int64
 4   driver_id    3128 non-null   str
 5   constructor  3128 non-null   str
dtypes: float64(2), int64(2), str(2)
memory usage: 146.8 KB

MISSING VALUES:
season            0
position       1464
points            0
wins              0
driver_id         0
constructor       0
dtype: int64

Duplicate rows: 0

Data Types:
season           int64
position       float64
points         float64
wins             int64
driver_id          str
constructor        str
dtype: object



============================================================
QUALIFYING DATAFRAME
============================================================

HEAD:

,season,round,driver_id,constructor_id,position,q1,q2,q3
11011,2026,2,bottas,cadillac,20,1:35.436,NaN,NaN
11012,2026,2,stroll,aston_martin,21,1:35.995,NaN,NaN
11013,2026,2,perez,cadillac,22,1:36.906,NaN,NaN
11014,2026,3,antonelli,mercedes,1,1:30.035,1:29.048,1:28.778
11015,2026,3,russell,mercedes,2,1:29.967,1:29.686,1:29.076
11016,2026,3,piastri,mclaren,3,1:30.200,1:29.451,1:29.132
11017,2026,3,leclerc,ferrari,4,1:29.915,1:29.303,1:29.405
11018,2026,3,norris,mclaren,5,1:30.401,1:29.795,1:29.409
11019,2026,3,hamilton,ferrari,6,1:30.309,1:29.589,1:29.567
11020,2026,3,gasly,alpine,7,1:30.584,1:29.874,1:29.691
11021,2026,3,hadjar,red_bull,8,1:30.662,1:30.104,1:29.978
11022,2026,3,bortoleto,audi,9,1:30.359,1:29.990,1:30.274
11023,2026,3,arvid_lindblad,rb,10,1:30.781,1:30.109,1:30.319
11024,2026,3,max_verstappen,red_bull,11,1:30.519,1:30.262,NaN
11025,2026,3,ocon,haas,12,1:30.915,1:30.309,NaN
11026,2026,3,hulkenberg,audi,13,1:30.358,1:30.387,NaN
11027,2026,3,lawson,rb,14,1:30.657,1:30.495,NaN
11028,2026,3,colapinto,alpine,15,1:30.931,1:30.627,NaN
11029,2026,3,sainz,williams,16,1:30.927,1:31.033,NaN
11030,2026,3,albon,williams,17,1:31.088,NaN,NaN
11031,2026,3,bearman,haas,18,1:31.090,NaN,NaN
11032,2026,3,perez,cadillac,19,1:32.206,NaN,NaN
11033,2026,3,bottas,cadillac,20,1:32.330,NaN,NaN
11034,2026,3,alonso,aston_martin,21,1:32.646,NaN,NaN
11035,2026,3,stroll,aston_martin,22,1:32.920,NaN,NaN

Shape: (11036, 8)

Columns:
['season', 'round', 'driver_id', 'constructor_id', 'position', 'q1', 'q2', 'q3']

INFO:
<class 'pandas.DataFrame'>
RangeIndex: 11036 entries, 0 to 11035
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   season          11036 non-null  int64
 1   round           11036 non-null  int64
 2   driver_id       11036 non-null  str
 3   constructor_id  11036 non-null  str
 4   position        11036 non-null  int64
 5   q1              10873 non-null  str
 6   q2              6248 non-null   str
 7   q3              3895 non-null   str
dtypes: int64(3), str(5)
memory usage: 689.9 KB

MISSING VALUES:
season               0
round                0
driver_id            0
constructor_id       0
position             0
q1                 163
q2                4788
q3                7141
dtype: int64

Duplicate rows: 0

Data Types:
season            int64
round             int64
driver_id           str
constructor_id      str
position          int64
q1                  str
q2                  str
q3                  str
dtype: object



============================================================
RACES DATAFRAME
============================================================

HEAD:

,season,round,race_name,circuit_id,date,time,url
1146,2025,22,Las Vegas Grand Prix,vegas,2025-11-23,04:00:00Z,https://en.wikipedia.org/wiki/2025_Las_Vegas_G...
1147,2025,23,Qatar Grand Prix,losail,2025-11-30,16:00:00Z,https://en.wikipedia.org/wiki/2025_Qatar_Grand...
1148,2025,24,Abu Dhabi Grand Prix,yas_marina,2025-12-07,13:00:00Z,https://en.wikipedia.org/wiki/2025_Abu_Dhabi_G...
1149,2026,1,Australian Grand Prix,albert_park,2026-03-08,04:00:00Z,https://en.wikipedia.org/wiki/2026_Australian_...
1150,2026,2,Chinese Grand Prix,shanghai,2026-03-15,07:00:00Z,https://en.wikipedia.org/wiki/2026_Chinese_Gra...
1151,2026,3,Japanese Grand Prix,suzuka,2026-03-29,05:00:00Z,https://en.wikipedia.org/wiki/2026_Japanese_Gr...
1152,2026,4,Miami Grand Prix,miami,2026-05-03,20:00:00Z,https://en.wikipedia.org/wiki/2026_Miami_Grand...
1153,2026,5,Canadian Grand Prix,villeneuve,2026-05-24,20:00:00Z,https://en.wikipedia.org/wiki/2026_Canadian_Gr...
1154,2026,6,Monaco Grand Prix,monaco,2026-06-07,13:00:00Z,https://en.wikipedia.org/wiki/2026_Monaco_Gran...
1155,2026,7,Barcelona Grand Prix,catalunya,2026-06-14,13:00:00Z,https://en.wikipedia.org/wiki/2026_Barcelona-C...
1156,2026,8,Austrian Grand Prix,red_bull_ring,2026-06-28,13:00:00Z,https://en.wikipedia.org/wiki/2026_Austrian_Gr...
1157,2026,9,British Grand Prix,silverstone,2026-07-05,14:00:00Z,https://en.wikipedia.org/wiki/2026_British_Gra...
1158,2026,10,Belgian Grand Prix,spa,2026-07-19,13:00:00Z,https://en.wikipedia.org/wiki/2026_Belgian_Gra...
1159,2026,11,Hungarian Grand Prix,hungaroring,2026-07-26,13:00:00Z,https://en.wikipedia.org/wiki/2026_Hungarian_G...
1160,2026,12,Dutch Grand Prix,zandvoort,2026-08-23,13:00:00Z,https://en.wikipedia.org/wiki/2026_Dutch_Grand...
1161,2026,13,Italian Grand Prix,monza,2026-09-06,13:00:00Z,https://en.wikipedia.org/wiki/2026_Italian_Gra...
1162,2026,14,Spanish Grand Prix,madring,2026-09-13,13:00:00Z,https://en.wikipedia.org/wiki/2026_Spanish_Gra...
1163,2026,15,Azerbaijan Grand Prix,baku,2026-09-26,11:00:00Z,https://en.wikipedia.org/wiki/2026_Azerbaijan_...
1164,2026,16,Singapore Grand Prix,marina_bay,2026-10-11,12:00:00Z,https://en.wikipedia.org/wiki/2026_Singapore_G...
1165,2026,17,United States Grand Prix,americas,2026-10-25,20:00:00Z,https://en.wikipedia.org/wiki/2026_United_Stat...
1166,2026,18,Mexico City Grand Prix,rodriguez,2026-11-01,20:00:00Z,https://en.wikipedia.org/wiki/2026_Mexico_City...
1167,2026,19,Brazilian Grand Prix,interlagos,2026-11-08,17:00:00Z,https://en.wikipedia.org/wiki/2026_Brazilian_G...
1168,2026,20,Las Vegas Grand Prix,vegas,2026-11-22,04:00:00Z,https://en.wikipedia.org/wiki/2026_Las_Vegas_G...
1169,2026,21,Qatar Grand Prix,losail,2026-11-29,16:00:00Z,https://en.wikipedia.org/wiki/2026_Qatar_Grand...
1170,2026,22,Abu Dhabi Grand Prix,yas_marina,2026-12-06,13:00:00Z,https://en.wikipedia.org/wiki/2026_Abu_Dhabi_G...

Shape: (1171, 7)

Columns:
['season', 'round', 'race_name', 'circuit_id', 'date', 'time', 'url']

INFO:
<class 'pandas.DataFrame'>
RangeIndex: 1171 entries, 0 to 1170
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   season      1171 non-null   int64
 1   round       1171 non-null   int64
 2   race_name   1171 non-null   str
 3   circuit_id  1171 non-null   str
 4   date        1171 non-null   str
 5   time        440 non-null    str
 6   url         1171 non-null   str
dtypes: int64(2), str(5)
memory usage: 64.2 KB

MISSING VALUES:
season          0
round           0
race_name       0
circuit_id      0
date            0
time          731
url             0
dtype: int64

Duplicate rows: 0

Data Types:
season        int64
round         int64
race_name       str
circuit_id      str
date            str
time            str
url             str
dtype: object



============================================================
RESULTS DATAFRAME
============================================================

HEAD:

,season,round,race_name,driver_id,driver_name,constructor_id,constructor,grid,position,points,laps,status,time,fastest_lap,fastest_lap_rank
25914,2026,2,Chinese Grand Prix,norris,Lando Norris,mclaren,McLaren,6,20,0.0,0,Did not start,NaN,NaN,NaN
25915,2026,2,Chinese Grand Prix,bortoleto,Gabriel Bortoleto,audi,Audi,16,21,0.0,0,Did not start,NaN,NaN,NaN
25916,2026,2,Chinese Grand Prix,albon,Alexander Albon,williams,Williams,22,22,0.0,0,Did not start,NaN,NaN,NaN
25917,2026,3,Japanese Grand Prix,antonelli,Andrea Kimi Antonelli,mercedes,Mercedes,1,1,25.0,53,Finished,1:28:03.403,1:32.432,1.0
25918,2026,3,Japanese Grand Prix,piastri,Oscar Piastri,mclaren,McLaren,3,2,18.0,53,Finished,+13.722,1:32.996,5.0
25919,2026,3,Japanese Grand Prix,leclerc,Charles Leclerc,ferrari,Ferrari,4,3,15.0,53,Finished,+15.270,1:32.634,3.0
25920,2026,3,Japanese Grand Prix,russell,George Russell,mercedes,Mercedes,2,4,12.0,53,Finished,+15.754,1:32.549,2.0
25921,2026,3,Japanese Grand Prix,norris,Lando Norris,mclaren,McLaren,5,5,10.0,53,Finished,+23.479,1:33.208,6.0
25922,2026,3,Japanese Grand Prix,hamilton,Lewis Hamilton,ferrari,Ferrari,6,6,8.0,53,Finished,+25.037,1:32.777,4.0
25923,2026,3,Japanese Grand Prix,gasly,Pierre Gasly,alpine,Alpine F1 Team,7,7,6.0,53,Finished,+32.340,1:33.691,9.0
25924,2026,3,Japanese Grand Prix,max_verstappen,Max Verstappen,red_bull,Red Bull,11,8,4.0,53,Finished,+32.677,1:33.552,8.0
25925,2026,3,Japanese Grand Prix,lawson,Liam Lawson,rb,RB F1 Team,14,9,2.0,53,Finished,+50.180,1:34.230,13.0
25926,2026,3,Japanese Grand Prix,ocon,Esteban Ocon,haas,Haas F1 Team,12,10,1.0,53,Finished,+51.216,1:34.256,14.0
25927,2026,3,Japanese Grand Prix,hulkenberg,Nico Hülkenberg,audi,Audi,13,11,0.0,53,Finished,+52.280,1:33.732,10.0
25928,2026,3,Japanese Grand Prix,hadjar,Isack Hadjar,red_bull,Red Bull,8,12,0.0,53,Finished,+56.154,1:33.837,11.0
25929,2026,3,Japanese Grand Prix,bortoleto,Gabriel Bortoleto,audi,Audi,9,13,0.0,53,Finished,+59.078,1:34.164,12.0
25930,2026,3,Japanese Grand Prix,arvid_lindblad,Arvid Lindblad,rb,RB F1 Team,10,14,0.0,53,Finished,+59.848,1:34.314,15.0
25931,2026,3,Japanese Grand Prix,sainz,Carlos Sainz,williams,Williams,16,15,0.0,53,Finished,+1:05.008,1:34.514,17.0
25932,2026,3,Japanese Grand Prix,colapinto,Franco Colapinto,alpine,Alpine F1 Team,15,16,0.0,53,Finished,+1:05.773,1:34.512,16.0
25933,2026,3,Japanese Grand Prix,perez,Sergio Pérez,cadillac,Cadillac F1 Team,19,17,0.0,53,Finished,+1:32.453,1:35.637,19.0
25934,2026,3,Japanese Grand Prix,alonso,Fernando Alonso,aston_martin,Aston Martin,21,18,0.0,52,Lapped,+26.548,1:36.221,20.0
25935,2026,3,Japanese Grand Prix,bottas,Valtteri Bottas,cadillac,Cadillac F1 Team,20,19,0.0,52,Lapped,+42.621,1:36.269,21.0
25936,2026,3,Japanese Grand Prix,albon,Alexander Albon,williams,Williams,17,20,0.0,51,Lapped,+5.067,1:33.427,7.0
25937,2026,3,Japanese Grand Prix,stroll,Lance Stroll,aston_martin,Aston Martin,22,21,0.0,30,Retired,NaN,1:37.217,22.0
25938,2026,3,Japanese Grand Prix,bearman,Oliver Bearman,haas,Haas F1 Team,18,22,0.0,20,Retired,NaN,1:35.604,18.0

Shape: (25939, 15)

Columns:
['season', 'round', 'race_name', 'driver_id', 'driver_name', 'constructor_id', 'constructor', 'grid', 'position', 'points', 'laps', 'status', 'time', 'fastest_lap', 'fastest_lap_rank']

INFO:
<class 'pandas.DataFrame'>
RangeIndex: 25939 entries, 0 to 25938
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   season            25939 non-null  int64
 1   round             25939 non-null  int64
 2   race_name         25939 non-null  str
 3   driver_id         25939 non-null  str
 4   driver_name       25939 non-null  str
 5   constructor_id    25939 non-null  str
 6   constructor       25939 non-null  str
 7   grid              25939 non-null  int64
 8   position          25939 non-null  int64
 9   points            25939 non-null  float64
 10  laps              25939 non-null  int64
 11  status            25939 non-null  str
 12  time              8354 non-null   str
 13  fastest_lap       8785 non-null   str
 14  fastest_lap_rank  8785 non-null   float64
dtypes: float64(2), int64(5), str(8)
memory usage: 3.0 MB

MISSING VALUES:
season                  0
round                   0
race_name               0
driver_id               0
driver_name             0
constructor_id          0
constructor             0
grid                    0
position                0
points                  0
laps                    0
status                  0
time                17585
fastest_lap         17154
fastest_lap_rank    17154
dtype: int64

Duplicate rows: 0

Data Types:
season                int64
round                 int64
race_name               str
driver_id               str
driver_name             str
constructor_id          str
constructor             str
grid                  int64
position              int64
points              float64
laps                  int64
status                  str
time                    str
fastest_lap             str
fastest_lap_rank    float64
dtype: object