In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
import os
import sys

sys.path.append(os.path.abspath(".."))

from src.load_data import load_all_data
from src.get_dfs import get_dfs
dfs = load_all_data()

(circuits,
constructors,
constructor_standings,
drivers,
driver_standings,
qualifying,
races,
results) = get_dfs(dfs)

In [9]:
# Find drivers with missing date of birth
missing_dob = drivers[drivers["dob"].isnull()]

# Display relevant columns
missing_dob[[
    "driver_id",
    "nationality"
]]

            driver_id nationality
31          paul_aron         NaN
62     dino_beganovic         NaN
124     luke_browning         NaN
187      jak_crawford         NaN
217  felipe_drugovich         NaN
221   alexander_dunne         NaN
277     antonio_fuoco         NaN
361      ryo_hirakawa         NaN
384       ayumu_iwasa         NaN
445    arthur_leclerc         NaN
497    victor_martins         NaN
564   patricio_o_ward         NaN
715      cian_shields         NaN
792    frederik_vesti         NaN

In [17]:
# Create clean copy
circuits_clean = circuits.copy()

# Drop unnecessary columns
circuits_clean = circuits_clean.drop(
    columns=["lat", "lng", "url"]
)

# Verify result
circuits_clean.head()

circuits_clean.to_csv(
    "../data/processed/circuits_clean.csv",
    index=False
)

In [18]:
# Create clean copy
constructors_clean = constructors.copy()

# Drop unnecessary columns
constructors_clean = constructors_clean.drop(
    columns=["url"]
)

# Verify result
constructors_clean.head()

constructors_clean.to_csv(
    "../data/processed/constructors_clean.csv",
    index=False
)

In [20]:
# Create clean copy
constructor_standings_clean = constructor_standings.copy()

# Drop unnecessary columns
constructor_standings_clean = constructor_standings_clean.drop(
    columns=["constructor"]
)

# Save cleaned dataframe
constructor_standings_clean.to_csv(
    "../data/processed/constructor_standings_clean.csv",
    index=False
)

# Verify result
constructor_standings_clean.head()

   season  position  points  wins constructor_id
0    1958       1.0    48.0     6        vanwall
1    1958       2.0    40.0     2        ferrari
2    1958       3.0    31.0     2         cooper
3    1958       4.0    18.0     0            brm
4    1958       5.0     6.0     0       maserati