In [167]:
from pathlib import Path
import pandas as pd

processed_root = Path(
    r"C:\Users\Ander\Desktop\F1-project\data\processed"
)

parquet_files = list(processed_root.rglob("*.parquet"))

print(f"Found {len(parquet_files)} parquet files")

Found 2159 parquet files

In [ ]:
from pathlib import Path
import pandas as pd

processed_root = Path(
    r"C:\Users\Ander\Desktop\F1-project\data\processed"
)

records = []

EXCLUDE_FILES = {
    "all_race_laps_metadata_enriched.parquet",
    "all_race_laps_metadata_with_times.parquet",
    "all_race_laps_metadata.parquet",
    "all_race_laps_metadata_enriched.parquet"
}


for file in processed_root.rglob("*.parquet"):

    if file.name in EXCLUDE_FILES:
        continue

    parts = file.parts

    filename = file.stem

    # -----------------------------
    # Parse metadata
    # -----------------------------

    try:
        race = parts[-3]
        session = parts[-2]
    except:
        race = None
        session = None

    # -----------------------------
    # Determine file type
    # -----------------------------

    if filename.endswith("_laps"):

        file_type = "laps"
        driver = filename.replace("_laps", "")

    elif filename in [
        "weather",
        "corners",
        "drivers",
        "rcm",
        "session_laptimes",
    ]:

        file_type = filename
        driver = None

    else:

        file_type = "telemetry"
        driver = filename

    records.append({
        "path": str(file),
        "race": race,
        "session": session,
        "type": file_type,
        "driver": driver,
    })

registry = pd.DataFrame(records)

display(registry.head())

print(registry.shape)

,path,race,session,type,driver
0,C:\Users\Ander\Desktop\F1-project\data\process...,Abu Dhabi Grand Prix,Qualifying,telemetry,ALB
1,C:\Users\Ander\Desktop\F1-project\data\process...,Abu Dhabi Grand Prix,Qualifying,laps,ALB
2,C:\Users\Ander\Desktop\F1-project\data\process...,Abu Dhabi Grand Prix,Qualifying,telemetry,ALO
3,C:\Users\Ander\Desktop\F1-project\data\process...,Abu Dhabi Grand Prix,Qualifying,laps,ALO
4,C:\Users\Ander\Desktop\F1-project\data\process...,Abu Dhabi Grand Prix,Qualifying,telemetry,ANT

(2156, 5)

In [169]:
# Inspect all telemetry files and load one telemetry dataframe

telemetry_registry = registry[registry["type"] == "telemetry"]


# Load first telemetry parquet
telemetry_path = telemetry_registry.iloc[0]["path"]

telemetry_df = pd.read_parquet(telemetry_path)


print(telemetry_df.columns)

Index(['time', 'rpm', 'speed', 'gear', 'throttle', 'brake', 'drs', 'distance',
       'rel_distance', 'DriverAhead', 'DistanceToDriverAhead', 'acc_x',
       'acc_y', 'acc_z', 'x', 'y', 'z', 'dataKey', 'race', 'session', 'driver',
       'lap'],
      dtype='str')

In [170]:
registry["type"].value_counts()

type
telemetry           958
laps                958
corners              48
drivers              48
rcm                  48
session_laptimes     48
weather              48
Name: count, dtype: int64

In [171]:
telemetry_features = [
    "speed",
    "throttle",
    "brake",
    "gear",
    "rpm",
    "drs",
    "acc_x",
    "acc_y",
    "acc_z",
    "rel_distance"
]

In [172]:
import sys
from pathlib import Path

# go up from notebooks/ to project root
sys.path.append(str(Path.cwd().parent))

In [173]:
from src.data.load_driver_telemetry import load_driver_session

import numpy as np
import pandas as pd

TARGET_POINTS = 500

all_laps = []

for row in registry.itertuples():

    # only race telemetry
    if row.type != "telemetry":
        continue

    if row.session != "Race":
        continue

    print(f"Processing {row.race} | {row.driver}")

    # load telemetry
    telemetry, _ = load_driver_session(
        registry,
        row.race,
        row.session,
        row.driver
    )

    telemetry = telemetry.sort_values(["lap", "time"])

    # process every lap
    for lap_number, lap_df in telemetry.groupby("lap"):

        # remove broken laps
        if len(lap_df) < 500:
            continue

        lap_df = (
            lap_df
            .sort_values("time")
            .drop_duplicates(subset="distance")
            .copy()
        )

        # skip invalid laps
        if lap_df["distance"].nunique() < 2:
            continue

        # normalize distance -> [0, 1]
        x_old = (
            lap_df["distance"] - lap_df["distance"].min()
        ) / (
            lap_df["distance"].max() - lap_df["distance"].min()
        )

        # target interpolation grid
        x_new = np.linspace(0, 1, TARGET_POINTS)

        interp_features = []

        # interpolate telemetry channels
        for col in telemetry_features:

            y_interp = np.interp(
                x_new,
                x_old,
                lap_df[col]
            )

            interp_features.append(y_interp)

        # shape -> (500, num_features)
        lap_tensor = np.stack(
            interp_features,
            axis=1
        )

        all_laps.append({
            "race": row.race,
            "driver": row.driver,
            "lap": lap_number,
            "tensor": lap_tensor
        })

# final ML tensor
X = np.stack([
    item["tensor"] for item in all_laps
])

print("Final tensor shape:")
print(X.shape)

print("Example lap tensor:")
print(X[0])

Processing Abu Dhabi Grand Prix | ALB
Processing Abu Dhabi Grand Prix | ALO
Processing Abu Dhabi Grand Prix | ANT
Processing Abu Dhabi Grand Prix | BEA
Processing Abu Dhabi Grand Prix | BOR
Processing Abu Dhabi Grand Prix | COL
Processing Abu Dhabi Grand Prix | GAS
Processing Abu Dhabi Grand Prix | HAD
Processing Abu Dhabi Grand Prix | HAM
Processing Abu Dhabi Grand Prix | HUL
Processing Abu Dhabi Grand Prix | LAW
Processing Abu Dhabi Grand Prix | LEC
Processing Abu Dhabi Grand Prix | NOR
Processing Abu Dhabi Grand Prix | OCO
Processing Abu Dhabi Grand Prix | PIA
Processing Abu Dhabi Grand Prix | RUS
Processing Abu Dhabi Grand Prix | SAI
Processing Abu Dhabi Grand Prix | STR
Processing Abu Dhabi Grand Prix | TSU
Processing Abu Dhabi Grand Prix | VER
Processing Australian Grand Prix | ALB
Processing Australian Grand Prix | ALO
Processing Australian Grand Prix | ANT
Processing Australian Grand Prix | BEA
Processing Australian Grand Prix | BOR
Processing Australian Grand Prix | DOO
Processing Australian Grand Prix | GAS
Processing Australian Grand Prix | HAD
Processing Australian Grand Prix | HAM
Processing Australian Grand Prix | HUL
Processing Australian Grand Prix | LAW
Processing Australian Grand Prix | LEC
Processing Australian Grand Prix | NOR
Processing Australian Grand Prix | OCO
Processing Australian Grand Prix | PIA
Processing Australian Grand Prix | RUS
Processing Australian Grand Prix | SAI
Processing Australian Grand Prix | STR
Processing Australian Grand Prix | TSU
Processing Australian Grand Prix | VER
Processing Austrian Grand Prix | ALB
Processing Austrian Grand Prix | ALO
Processing Austrian Grand Prix | ANT
Processing Austrian Grand Prix | BEA
Processing Austrian Grand Prix | BOR
Processing Austrian Grand Prix | COL
Processing Austrian Grand Prix | GAS
Processing Austrian Grand Prix | HAD
Processing Austrian Grand Prix | HAM
Processing Austrian Grand Prix | HUL
Processing Austrian Grand Prix | LAW
Processing Austrian Grand Prix | LEC
Processing Austrian Grand Prix | NOR
Processing Austrian Grand Prix | OCO
Processing Austrian Grand Prix | PIA
Processing Austrian Grand Prix | RUS
Processing Austrian Grand Prix | SAI
Processing Austrian Grand Prix | STR
Processing Austrian Grand Prix | TSU
Processing Austrian Grand Prix | VER
Processing Azerbaijan Grand Prix | ALB
Processing Azerbaijan Grand Prix | ALO
Processing Azerbaijan Grand Prix | ANT
Processing Azerbaijan Grand Prix | BEA
Processing Azerbaijan Grand Prix | BOR
Processing Azerbaijan Grand Prix | COL
Processing Azerbaijan Grand Prix | GAS
Processing Azerbaijan Grand Prix | HAD
Processing Azerbaijan Grand Prix | HAM
Processing Azerbaijan Grand Prix | HUL
Processing Azerbaijan Grand Prix | LAW
Processing Azerbaijan Grand Prix | LEC
Processing Azerbaijan Grand Prix | NOR
Processing Azerbaijan Grand Prix | OCO
Processing Azerbaijan Grand Prix | PIA
Processing Azerbaijan Grand Prix | RUS
Processing Azerbaijan Grand Prix | SAI
Processing Azerbaijan Grand Prix | STR
Processing Azerbaijan Grand Prix | TSU
Processing Azerbaijan Grand Prix | VER
Processing Bahrain Grand Prix | ALB
Processing Bahrain Grand Prix | ALO
Processing Bahrain Grand Prix | ANT
Processing Bahrain Grand Prix | BEA
Processing Bahrain Grand Prix | BOR
Processing Bahrain Grand Prix | DOO
Processing Bahrain Grand Prix | GAS
Processing Bahrain Grand Prix | HAD
Processing Bahrain Grand Prix | HAM
Processing Bahrain Grand Prix | HUL
Processing Bahrain Grand Prix | LAW
Processing Bahrain Grand Prix | LEC
Processing Bahrain Grand Prix | NOR
Processing Bahrain Grand Prix | OCO
Processing Bahrain Grand Prix | PIA
Processing Bahrain Grand Prix | RUS
Processing Bahrain Grand Prix | SAI
Processing Bahrain Grand Prix | STR
Processing Bahrain Grand Prix | TSU
Processing Bahrain Grand Prix | VER
Processing Belgian Grand Prix | ALB
Processing Belgian Grand Prix | ALO
Processing Belgian Grand Prix | ANT
Processing Belgian Grand Prix | BEA
Processing Belgian Grand Prix | BOR
Processing Belgian Grand Prix | COL
Processing Belgian Grand Prix | GAS
Processing Belgian Grand Prix | HAD
Processing Belgian Grand Prix | HAM
Processing Belgian Grand Prix | HUL
Processing Belgian Grand Prix | LAW
Processing Belgian Grand Prix | LEC
Processing Belgian Grand Prix | NOR
Processing Belgian Grand Prix | OCO
Processing Belgian Grand Prix | PIA
Processing Belgian Grand Prix | RUS
Processing Belgian Grand Prix | SAI
Processing Belgian Grand Prix | STR
Processing Belgian Grand Prix | TSU
Processing Belgian Grand Prix | VER
Processing British Grand Prix | ALB
Processing British Grand Prix | ALO
Processing British Grand Prix | ANT
Processing British Grand Prix | BEA
Processing British Grand Prix | BOR
Processing British Grand Prix | COL
Processing British Grand Prix | GAS
Processing British Grand Prix | HAD
Processing British Grand Prix | HAM
Processing British Grand Prix | HUL
Processing British Grand Prix | LAW
Processing British Grand Prix | LEC
Processing British Grand Prix | NOR
Processing British Grand Prix | OCO
Processing British Grand Prix | PIA
Processing British Grand Prix | RUS
Processing British Grand Prix | SAI
Processing British Grand Prix | STR
Processing British Grand Prix | TSU
Processing British Grand Prix | VER
Processing Canadian Grand Prix | ALB
Processing Canadian Grand Prix | ALO
Processing Canadian Grand Prix | ANT
Processing Canadian Grand Prix | BEA
Processing Canadian Grand Prix | BOR
Processing Canadian Grand Prix | COL
Processing Canadian Grand Prix | GAS
Processing Canadian Grand Prix | HAD
Processing Canadian Grand Prix | HAM
Processing Canadian Grand Prix | HUL
Processing Canadian Grand Prix | LAW
Processing Canadian Grand Prix | LEC
Processing Canadian Grand Prix | NOR
Processing Canadian Grand Prix | OCO
Processing Canadian Grand Prix | PIA
Processing Canadian Grand Prix | RUS
Processing Canadian Grand Prix | SAI
Processing Canadian Grand Prix | STR
Processing Canadian Grand Prix | TSU
Processing Canadian Grand Prix | VER
Processing Chinese Grand Prix | ALB
Processing Chinese Grand Prix | ALO
Processing Chinese Grand Prix | ANT
Processing Chinese Grand Prix | BEA
Processing Chinese Grand Prix | BOR
Processing Chinese Grand Prix | DOO
Processing Chinese Grand Prix | GAS
Processing Chinese Grand Prix | HAD
Processing Chinese Grand Prix | HAM
Processing Chinese Grand Prix | HUL
Processing Chinese Grand Prix | LAW
Processing Chinese Grand Prix | LEC
Processing Chinese Grand Prix | NOR
Processing Chinese Grand Prix | OCO
Processing Chinese Grand Prix | PIA
Processing Chinese Grand Prix | RUS
Processing Chinese Grand Prix | SAI
Processing Chinese Grand Prix | STR
Processing Chinese Grand Prix | TSU
Processing Chinese Grand Prix | VER
Processing Dutch Grand Prix | ALB
Processing Dutch Grand Prix | ALO
Processing Dutch Grand Prix | ANT
Processing Dutch Grand Prix | BEA
Processing Dutch Grand Prix | BOR
Processing Dutch Grand Prix | COL
Processing Dutch Grand Prix | GAS
Processing Dutch Grand Prix | HAD
Processing Dutch Grand Prix | HAM
Processing Dutch Grand Prix | HUL
Processing Dutch Grand Prix | LAW
Processing Dutch Grand Prix | LEC
Processing Dutch Grand Prix | NOR
Processing Dutch Grand Prix | OCO
Processing Dutch Grand Prix | PIA
Processing Dutch Grand Prix | RUS
Processing Dutch Grand Prix | SAI
Processing Dutch Grand Prix | STR
Processing Dutch Grand Prix | TSU
Processing Dutch Grand Prix | VER
Processing Emilia Romagna Grand Prix | ALB
Processing Emilia Romagna Grand Prix | ALO
Processing Emilia Romagna Grand Prix | ANT
Processing Emilia Romagna Grand Prix | BEA
Processing Emilia Romagna Grand Prix | BOR
Processing Emilia Romagna Grand Prix | COL
Processing Emilia Romagna Grand Prix | GAS
Processing Emilia Romagna Grand Prix | HAD
Processing Emilia Romagna Grand Prix | HAM
Processing Emilia Romagna Grand Prix | HUL
Processing Emilia Romagna Grand Prix | LAW
Processing Emilia Romagna Grand Prix | LEC
Processing Emilia Romagna Grand Prix | NOR
Processing Emilia Romagna Grand Prix | OCO
Processing Emilia Romagna Grand Prix | PIA
Processing Emilia Romagna Grand Prix | RUS
Processing Emilia Romagna Grand Prix | SAI
Processing Emilia Romagna Grand Prix | STR
Processing Emilia Romagna Grand Prix | TSU
Processing Emilia Romagna Grand Prix | VER
Processing Hungarian Grand Prix | ALB
Processing Hungarian Grand Prix | ALO
Processing Hungarian Grand Prix | ANT
Processing Hungarian Grand Prix | BEA
Processing Hungarian Grand Prix | BOR
Processing Hungarian Grand Prix | COL
Processing Hungarian Grand Prix | GAS
Processing Hungarian Grand Prix | HAD
Processing Hungarian Grand Prix | HAM
Processing Hungarian Grand Prix | HUL
Processing Hungarian Grand Prix | LAW
Processing Hungarian Grand Prix | LEC
Processing Hungarian Grand Prix | NOR
Processing Hungarian Grand Prix | OCO
Processing Hungarian Grand Prix | PIA
Processing Hungarian Grand Prix | RUS
Processing Hungarian Grand Prix | SAI
Processing Hungarian Grand Prix | STR
Processing Hungarian Grand Prix | TSU
Processing Hungarian Grand Prix | VER
Processing Italian Grand Prix | ALB
Processing Italian Grand Prix | ALO
Processing Italian Grand Prix | ANT
Processing Italian Grand Prix | BEA
Processing Italian Grand Prix | BOR
Processing Italian Grand Prix | COL
Processing Italian Grand Prix | GAS
Processing Italian Grand Prix | HAD
Processing Italian Grand Prix | HAM
Processing Italian Grand Prix | HUL
Processing Italian Grand Prix | LAW
Processing Italian Grand Prix | LEC
Processing Italian Grand Prix | NOR
Processing Italian Grand Prix | OCO
Processing Italian Grand Prix | PIA
Processing Italian Grand Prix | RUS
Processing Italian Grand Prix | SAI
Processing Italian Grand Prix | STR
Processing Italian Grand Prix | TSU
Processing Italian Grand Prix | VER
Processing Japanese Grand Prix | ALB
Processing Japanese Grand Prix | ALO
Processing Japanese Grand Prix | ANT
Processing Japanese Grand Prix | BEA
Processing Japanese Grand Prix | BOR
Processing Japanese Grand Prix | DOO
Processing Japanese Grand Prix | GAS
Processing Japanese Grand Prix | HAD
Processing Japanese Grand Prix | HAM
Processing Japanese Grand Prix | HUL
Processing Japanese Grand Prix | LAW
Processing Japanese Grand Prix | LEC
Processing Japanese Grand Prix | NOR
Processing Japanese Grand Prix | OCO
Processing Japanese Grand Prix | PIA
Processing Japanese Grand Prix | RUS
Processing Japanese Grand Prix | SAI
Processing Japanese Grand Prix | STR
Processing Japanese Grand Prix | TSU
Processing Japanese Grand Prix | VER
Processing Las Vegas Grand Prix | ALB
Processing Las Vegas Grand Prix | ALO
Processing Las Vegas Grand Prix | ANT
Processing Las Vegas Grand Prix | BEA
Processing Las Vegas Grand Prix | BOR
Processing Las Vegas Grand Prix | COL
Processing Las Vegas Grand Prix | GAS
Processing Las Vegas Grand Prix | HAD
Processing Las Vegas Grand Prix | HAM
Processing Las Vegas Grand Prix | HUL
Processing Las Vegas Grand Prix | LAW
Processing Las Vegas Grand Prix | LEC
Processing Las Vegas Grand Prix | NOR
Processing Las Vegas Grand Prix | OCO
Processing Las Vegas Grand Prix | PIA
Processing Las Vegas Grand Prix | RUS
Processing Las Vegas Grand Prix | SAI
Processing Las Vegas Grand Prix | STR
Processing Las Vegas Grand Prix | TSU
Processing Las Vegas Grand Prix | VER
Processing Mexico City Grand Prix | ALB
Processing Mexico City Grand Prix | ALO
Processing Mexico City Grand Prix | ANT
Processing Mexico City Grand Prix | BEA
Processing Mexico City Grand Prix | BOR
Processing Mexico City Grand Prix | COL
Processing Mexico City Grand Prix | GAS
Processing Mexico City Grand Prix | HAD
Processing Mexico City Grand Prix | HAM
Processing Mexico City Grand Prix | HUL
Processing Mexico City Grand Prix | LAW
Processing Mexico City Grand Prix | LEC
Processing Mexico City Grand Prix | NOR
Processing Mexico City Grand Prix | OCO
Processing Mexico City Grand Prix | PIA
Processing Mexico City Grand Prix | RUS
Processing Mexico City Grand Prix | SAI
Processing Mexico City Grand Prix | STR
Processing Mexico City Grand Prix | TSU
Processing Mexico City Grand Prix | VER
Processing Miami Grand Prix | ALB
Processing Miami Grand Prix | ALO
Processing Miami Grand Prix | ANT
Processing Miami Grand Prix | BEA
Processing Miami Grand Prix | BOR
Processing Miami Grand Prix | DOO
Processing Miami Grand Prix | GAS
Processing Miami Grand Prix | HAD
Processing Miami Grand Prix | HAM
Processing Miami Grand Prix | HUL
Processing Miami Grand Prix | LAW
Processing Miami Grand Prix | LEC
Processing Miami Grand Prix | NOR
Processing Miami Grand Prix | OCO
Processing Miami Grand Prix | PIA
Processing Miami Grand Prix | RUS
Processing Miami Grand Prix | SAI
Processing Miami Grand Prix | STR
Processing Miami Grand Prix | TSU
Processing Miami Grand Prix | VER
Processing Monaco Grand Prix | ALB
Processing Monaco Grand Prix | ALO
Processing Monaco Grand Prix | ANT
Processing Monaco Grand Prix | BEA
Processing Monaco Grand Prix | BOR
Processing Monaco Grand Prix | COL
Processing Monaco Grand Prix | GAS
Processing Monaco Grand Prix | HAD
Processing Monaco Grand Prix | HAM
Processing Monaco Grand Prix | HUL
Processing Monaco Grand Prix | LAW
Processing Monaco Grand Prix | LEC
Processing Monaco Grand Prix | NOR
Processing Monaco Grand Prix | OCO
Processing Monaco Grand Prix | PIA
Processing Monaco Grand Prix | RUS
Processing Monaco Grand Prix | SAI
Processing Monaco Grand Prix | STR
Processing Monaco Grand Prix | TSU
Processing Monaco Grand Prix | VER
Processing Qatar Grand Prix | ALB
Processing Qatar Grand Prix | ALO
Processing Qatar Grand Prix | ANT
Processing Qatar Grand Prix | BEA
Processing Qatar Grand Prix | BOR
Processing Qatar Grand Prix | COL
Processing Qatar Grand Prix | GAS
Processing Qatar Grand Prix | HAD
Processing Qatar Grand Prix | HAM
Processing Qatar Grand Prix | HUL
Processing Qatar Grand Prix | LAW
Processing Qatar Grand Prix | LEC
Processing Qatar Grand Prix | NOR
Processing Qatar Grand Prix | OCO
Processing Qatar Grand Prix | PIA
Processing Qatar Grand Prix | RUS
Processing Qatar Grand Prix | SAI
Processing Qatar Grand Prix | STR
Processing Qatar Grand Prix | TSU
Processing Qatar Grand Prix | VER
Processing Saudi Arabian Grand Prix | ALB
Processing Saudi Arabian Grand Prix | ALO
Processing Saudi Arabian Grand Prix | ANT
Processing Saudi Arabian Grand Prix | BEA
Processing Saudi Arabian Grand Prix | BOR
Processing Saudi Arabian Grand Prix | DOO
Processing Saudi Arabian Grand Prix | GAS
Processing Saudi Arabian Grand Prix | HAD
Processing Saudi Arabian Grand Prix | HAM
Processing Saudi Arabian Grand Prix | HUL
Processing Saudi Arabian Grand Prix | LAW
Processing Saudi Arabian Grand Prix | LEC
Processing Saudi Arabian Grand Prix | NOR
Processing Saudi Arabian Grand Prix | OCO
Processing Saudi Arabian Grand Prix | PIA
Processing Saudi Arabian Grand Prix | RUS
Processing Saudi Arabian Grand Prix | SAI
Processing Saudi Arabian Grand Prix | STR
Processing Saudi Arabian Grand Prix | TSU
Processing Saudi Arabian Grand Prix | VER
Processing Singapore Grand Prix | ALB
Processing Singapore Grand Prix | ALO
Processing Singapore Grand Prix | ANT
Processing Singapore Grand Prix | BEA
Processing Singapore Grand Prix | BOR
Processing Singapore Grand Prix | COL
Processing Singapore Grand Prix | GAS
Processing Singapore Grand Prix | HAD
Processing Singapore Grand Prix | HAM
Processing Singapore Grand Prix | HUL
Processing Singapore Grand Prix | LAW
Processing Singapore Grand Prix | LEC
Processing Singapore Grand Prix | NOR
Processing Singapore Grand Prix | OCO
Processing Singapore Grand Prix | PIA
Processing Singapore Grand Prix | RUS
Processing Singapore Grand Prix | SAI
Processing Singapore Grand Prix | STR
Processing Singapore Grand Prix | TSU
Processing Singapore Grand Prix | VER
Processing Spanish Grand Prix | ALB
Processing Spanish Grand Prix | ALO
Processing Spanish Grand Prix | ANT
Processing Spanish Grand Prix | BEA
Processing Spanish Grand Prix | BOR
Processing Spanish Grand Prix | COL
Processing Spanish Grand Prix | GAS
Processing Spanish Grand Prix | HAD
Processing Spanish Grand Prix | HAM
Processing Spanish Grand Prix | HUL
Processing Spanish Grand Prix | LAW
Processing Spanish Grand Prix | LEC
Processing Spanish Grand Prix | NOR
Processing Spanish Grand Prix | OCO
Processing Spanish Grand Prix | PIA
Processing Spanish Grand Prix | RUS
Processing Spanish Grand Prix | SAI
Processing Spanish Grand Prix | TSU
Processing Spanish Grand Prix | VER
Processing São Paulo Grand Prix | ALB
Processing São Paulo Grand Prix | ALO
Processing São Paulo Grand Prix | ANT
Processing São Paulo Grand Prix | BEA
Processing São Paulo Grand Prix | BOR
Processing São Paulo Grand Prix | COL
Processing São Paulo Grand Prix | GAS
Processing São Paulo Grand Prix | HAD
Processing São Paulo Grand Prix | HAM
Processing São Paulo Grand Prix | HUL
Processing São Paulo Grand Prix | LAW
Processing São Paulo Grand Prix | LEC
Processing São Paulo Grand Prix | NOR
Processing São Paulo Grand Prix | OCO
Processing São Paulo Grand Prix | PIA
Processing São Paulo Grand Prix | RUS
Processing São Paulo Grand Prix | SAI
Processing São Paulo Grand Prix | STR
Processing São Paulo Grand Prix | TSU
Processing São Paulo Grand Prix | VER
Processing United States Grand Prix | ALB
Processing United States Grand Prix | ALO
Processing United States Grand Prix | ANT
Processing United States Grand Prix | BEA
Processing United States Grand Prix | BOR
Processing United States Grand Prix | COL
Processing United States Grand Prix | GAS
Processing United States Grand Prix | HAD
Processing United States Grand Prix | HAM
Processing United States Grand Prix | HUL
Processing United States Grand Prix | LAW
Processing United States Grand Prix | LEC
Processing United States Grand Prix | NOR
Processing United States Grand Prix | OCO
Processing United States Grand Prix | PIA
Processing United States Grand Prix | RUS
Processing United States Grand Prix | SAI
Processing United States Grand Prix | STR
Processing United States Grand Prix | TSU
Processing United States Grand Prix | VER
Final tensor shape:
(26666, 500, 10)
Example lap tensor:
[[ 0.00000000e+00  2.10000000e+01  1.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  3.85355662e-07]
 [ 5.12323575e+01  4.48215717e+01  0.00000000e+00 ...  9.81207786e-01
   3.21038284e-01  1.99245550e-03]
 [ 7.50510792e+01  6.59225901e+01  0.00000000e+00 ...  2.26490717e-01
  -1.11120952e-01  3.99284367e-03]
 ...
 [ 2.07796242e+02  1.00000000e+02  0.00000000e+00 ...  2.32828001e+00
   9.87137301e-01  9.94184989e-01]
 [ 2.14206144e+02  1.00000000e+02  0.00000000e+00 ...  2.49250096e+00
   6.03882729e-01  9.96185377e-01]
 [ 2.20536377e+02  1.00000000e+02  0.00000000e+00 ...  2.65552102e+00
   3.38586157e-01  9.98185765e-01]]

In [174]:
all_laps_df = pd.DataFrame([
    {
        "idx": i,
        "race": item["race"],
        "driver": item["driver"],
        "lap": item["lap"]
    }
    for i, item in enumerate(all_laps)
])

SAVE_DIR = r"C:/Users/Ander/Desktop/F1-project/data/processed"

# save tensor
np.save(f"{SAVE_DIR}/all_race_laps_tensor.npy", X)

# save metadata
all_laps_df.to_parquet(
    f"{SAVE_DIR}/all_race_laps_metadata.parquet",
    index=False
)

print("Saved successfully")

Saved successfully

In [175]:
from src.data.load_driver_telemetry import load_driver_session

_ , ham = load_driver_session(
    registry,
    "Monaco Grand Prix",
    "Race",
    "HAM"
)

display(ham[ham["lap"] == 1][["time"]])

# load saved files
X = np.load(
    r"C:/Users/Ander/Desktop/F1-project/data/processed/all_race_laps_tensor.npy"
)

laps = pd.read_parquet(
    r"C:/Users/Ander/Desktop/F1-project/data/processed/all_race_laps_metadata.parquet"
)

# find Monaco HAM lap 1
result = laps[
    (laps["race"] == "Monaco Grand Prix") &
    (laps["driver"] == "HAM") &
    (laps["lap"] == 1)
]

display(result)

idx = result.iloc[0]["idx"]

print(idx)

lap_tensor = X[idx]

print(lap_tensor.shape)

     time
0  89.406

         idx               race driver  lap
19030  19030  Monaco Grand Prix    HAM    1

19030
(500, 10)

In [176]:
import numpy as np
import pandas as pd
from tqdm import tqdm

# existing data
X = np.load(
    r"C:/Users/Ander/Desktop/F1-project/data/processed/all_race_laps_tensor.npy"
)

laps = pd.read_parquet(
    r"C:/Users/Ander/Desktop/F1-project/data/processed/all_race_laps_metadata.parquet"
)

lap_times = []

for _, row in tqdm(laps.iterrows(), total=len(laps)):

    try:
        _, session = load_driver_session(
            registry,
            row["race"],
            "Race",
            row["driver"]
        )

        lap_time = session[
            session["lap"] == row["lap"]
        ]["time"].iloc[0]

        lap_times.append(float(lap_time))

    except Exception as e:

        print(
            f"Failed: {row['race']} "
            f"{row['driver']} lap {row['lap']}"
        )

        lap_times.append(np.nan)

laps["lap_time"] = lap_times

  5%|▌         | 1410/26666 [00:48<13:50, 30.42it/s]

Failed: Australian Grand Prix DOO lap 1

  7%|▋         | 1911/26666 [01:06<10:01, 41.17it/s]

Failed: Australian Grand Prix SAI lap 1

  8%|▊         | 2172/26666 [01:14<09:50, 41.51it/s]

Failed: Austrian Grand Prix ANT lap 1

 12%|█▏        | 3208/26666 [01:49<13:07, 29.77it/s]

Failed: Austrian Grand Prix VER lap 1

 15%|█▍        | 3921/26666 [02:12<10:36, 35.76it/s]

Failed: Azerbaijan Grand Prix PIA lap 1

 25%|██▍       | 6538/26666 [03:59<13:48, 24.30it/s]

Failed: British Grand Prix LAW lap 1

 61%|██████    | 16161/26666 [09:50<06:06, 28.63it/s]

Failed: Las Vegas Grand Prix STR lap 1

 67%|██████▋   | 17759/26666 [10:59<04:39, 31.88it/s]

Failed: Miami Grand Prix DOO lap 1

 80%|███████▉  | 21323/26666 [13:17<02:22, 37.37it/s]

Failed: Saudi Arabian Grand Prix GAS lap 1

 92%|█████████▏| 24638/26666 [14:59<01:03, 31.96it/s]

Failed: São Paulo Grand Prix BOR lap 1

100%|██████████| 26666/26666 [15:57<00:00, 27.84it/s]

In [177]:
valid_mask = ~laps["lap_time"].isna()

laps = laps[valid_mask].reset_index(drop=True)

X = X[valid_mask.values]

In [178]:
laps.to_parquet(
    r"C:/Users/Ander/Desktop/F1-project/data/processed/all_race_laps_metadata_with_times.parquet"
)

np.save(
    r"C:/Users/Ander/Desktop/F1-project/data/processed/all_race_laps_tensor_clean.npy",
    X
)